#!/bin/bash
export GRUPO_VIAS_EMAIL_TO=postventa@grupovias.cl
export GRUPO_VIAS_EMAIL_CC=pbrignardello@grupovias.cl,goviedo@sb.cl,goviedo.sevenit@gmail.com
export GRUPO_VIAS_EMAIL_INTERVALO=172800
export JAVA_HOME=/opt/jdks/correto-21
git fetch && git pull
./mvnw clean compile package install
java -jar target/grupovias-0.0.1-SNAPSHOT.jar >> log.txt &


